version: '2.1'

services:

  mysql:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mysql
    healthcheck:
      test: "exit 0"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
    - 80:1337
    depends_on:
      mysql:
        condition: service_healthy
    container_name: back-end
    volumes:
      - ./back-end:/usr/src/app
#    links:
#        - mysql


volumes:
  mysql-data:



