/**
 Generated by sails-inverse-model
 Date:Sun Oct 07 2018 11:23:28 GMT+1300 (NZDT)
 */
var moment = require('moment');
module.exports = {
  attributes: {
    name: {
      type: "string",

    },

    //Relaciones
    employee: {
      collection: "employees",
      via: "company_id"
    },
    ecps: {
      collection: "epcs",
      via: "company_id"
    },
    products: {
      collection: "products",
      via: "company_id"
    },
    shops: {
      collection: "shops",
      via: "company_id"
    }
  },
  customToJSON: function () {
    if (this.createdAt) {
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if (this.updatedAt) {
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  }
};
