/**
 Generated by sails-inverse-model
 Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
 */
var moment = require('moment');
module.exports = {
  attributes: {
    employee: {
      model: "employees",
      columnName: "employee_id",
      required: true
    },
    inventory: {
      model: "inventories",
      columnName: "inventory_id",
      required: true
    }
  },
  customToJSON: function () {
    if (typeof this.employee == "number")
      this.employee = {
        id: this.employee
      };
    if (typeof this.inventory == "number")
      this.inventory = {
        id: this.inventory
      };
    if (this.createdAt) {
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if (this.updatedAt) {
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  },
  tableName: "employees_inventories"
};
