/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/

module.exports = {
    attributes: {
        fecha: {
          type: 'ref', columnType: 'datetime', autoCreatedAt: true
        },
        parcial: {
            type: "number",

        },
        colaborativo: {
            type: "number",

        },
        zonas_id: {
            model: "zonas",
            required: true
        },
        inventarios_consolidados_id: {
          model: "inventariosConsolidados",
          required: false
        },

        //Relaciones
        productos_zona:{
          collection: 'productosZona',
          via: 'inventarios_id',
          through: 'inventariosProductos'
        },
        users:{
          collection:'empleados',
          via:'inventarios_id',
          through:'usersInventarios'
        }
    }
};
