/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/
var moment = require('moment');
module.exports = {
    attributes: {
        fecha: {
          type: 'ref', columnType: 'datetime', autoCreatedAt: true
        },
        parcial: {
            type: "number",
        },
        colaborativo: {
            type: "number",
        },
        zonas_id: {
            model: "zonas",
            required: true
        },
        inventarios_consolidados_id: {
          model: "inventariosConsolidados",
          required: false
        },
        //region Relaciones
        productos_zona:{
          collection: 'productosZona',
          via: 'inventarios_id',
          through: 'inventariosProductos'
        },
        users:{
          collection:'empleados',
          via:'inventarios_id',
          through:'usersInventarios'
        }
        //endregion
    },
  customToJSON: function() {
    //Si no se obtiene algun producto asociado, se retorna un objecto
    if(typeof this.zonas_id =="number")
      this.zonas_id = {
        id: this.zonas_id
      };
    if(typeof this.inventarios_consolidados_id =="number")
      this.inventarios_consolidados_id = {
        id: this.inventarios_consolidados_id
      };
    if(this.fecha){
      this.fecha = moment(this.fecha).format("YYYY-MM-DDTHH:mm:ss");
    }
    if(this.createdAt){
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if(this.updatedAt){
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  }
};
