/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/

module.exports = {
    attributes: {
      name: {type: 'string'},
      empleados_id: {
        model: "empleados",
        required: true
      },
      //Relaciones
      inventarios:{
        collection: 'inventarios',
        via: 'inventarios_consolidados_id'
      }
    },
  customToJSON: function() {
    //Si no se obtiene algun producto asociado, se retorna un objecto
    if(typeof this.empleados_id =="number")
      this.empleados_id = {
        id: this.empleados_id
      };
    return this;
  },
  tableName: 'inventarios_consolidados'
};
