/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/
var moment = require('moment');
module.exports = {
    attributes: {
        name:{type: "string"},
        companias_id: {
            model: "companias",
            required: true
        },
        //Relaciones
        empleados:{
          collection: "empleados",
          via: "locales_id"
        },
        zonas:{
          collection: "zonas",
          via:"locales_id"
        }

    },
  customToJSON: function() {
    //Si no se obtiene algun producto asociado, se retorna un objecto
    if(typeof this.companias_id =="number")
      this.companias_id = {
        id: this.companias_id
      };

    if(this.createdAt){
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if(this.updatedAt){
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  },
};
