/**
 Generated by sails-inverse-model
 Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
 */
module.exports = {

  attributes: {
    productos_id: {
      model: "productos",
      required: true
    },
    zonas_id: {
      model: "zonas",
      required: true
    },
    fecha_ingreso: {
      type: 'ref', columnType: 'datetime', autoCreatedAt: true
    },
    fecha_venta: {
      type: 'ref', columnType: 'datetime',
    },
    fecha_devolucion: {
      type: 'ref', columnType: 'datetime',
    },
    devolucion_observaciones: {
      type: "string"
    },
    devoluciones_id: {
      model: "devoluciones"
    },
    logs_usuarios: {
      type: "string"
    },
    ventas_id: {
      model: "ventas"
    },
    epcs_id: {
      model: "epcs",
      required: true
    },
    //Relaciones muchos a muchos
    inventarios:{
      collection: 'inventarios',
      via: 'productos_zona_id',
      through: 'inventariosProductos'
    }

  },
  beforeCreate: function (valuesToSet, proceed) {
    //Valido que el epc sea valido (lo busco por el epc y que el estado sea 0 -sin usar)

      try{
        Epcs.find({
          id: valuesToSet.epcs_id,
          state: 0
        }).then(function (epc) {
          if(epc && epc.length>0){
            return proceed();
          }else
            var err=new Error();
            err.bd=true;
            err.propio=true;
            err.number = 'error_EPC01';
            return proceed(err);
        }).catch(function (err) {
          err.bd=true;
          err.propio=false;
          return proceed(err)
        });
      }catch(err){
        err.bd=false;
        err.propio=false;
        return proceed(err)
      }

  },
  tableName: 'productos_zona'
};
