/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/

module.exports = {
    attributes: {
        productos_zona_id: {
            model: "productosZona",
            required: true
        },
        transferencias_id: {
            model: "transferencias",
            required: true
        },
        estado: {
            type: "number",
        },
    },

  customToJSON: function() {
    //Si no se obtiene algun producto asociado, se retorna un objecto
    if(typeof this.productos_zona_id =="number")
      this.productos_zona_id = {
        id: this.productos_zona_id
      };
    if(typeof this.transferencias_id =="number")
      this.transferencias_id = {
        id: this.transferencias_id
      };

    return this;
  },
  tableName:"productos_zona_has_transferencias",

  beforeCreate: function (valuesToSet, proceed) {

    ProductosZonaHasTransferencias.find({
      productos_zona_id: valuesToSet.productos_zona_id,
      estado: 0
    })
      .then(function (productoZonaHasTransferencia) {
        //No puede existir el mismo producto en transferencia a la vez
        if(productoZonaHasTransferencia)
              return proceed('error_PZHT01');
        else
          return proceed();
    });

  }
};
