/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/
var moment = require('moment');
module.exports = {
    attributes: {
        productos_zona_id: {
            model: "productosZona",
            required: true
        },
        transferencias_id: {
            model: "transferencias",
            required: true
        },
        estado: {
            type: "boolean",
        },
    },

  customToJSON: function() {
    //Si no se obtiene algun producto asociado, se retorna un objecto
    if(typeof this.productos_zona_id =="number")
      this.productos_zona_id = {
        id: this.productos_zona_id
      };
    if(typeof this.transferencias_id =="number")
      this.transferencias_id = {
        id: this.transferencias_id
      };

    if(this.createdAt){
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if(this.updatedAt){
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  },
  tableName:"productos_zona_has_transferencias",

  beforeCreate: function (valuesToSet, proceed) {

    ProductosZonaHasTransferencias.findOne({
      productos_zona_id: valuesToSet.productos_zona_id,
      estado: 0
    })
      .then(function (productoZonaHasTransferencia) {
        //No puede existir el mismo producto en transferencia a la vez
        if(productoZonaHasTransferencia)
              return proceed('error_PZHT01');
        else
          return proceed();
    }).catch(function (error) {
      return proceed(error);
    });

  }
};
