/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/
var moment = require('moment');
module.exports = {
    attributes: {
        productos_zona_id: {
            model: "productosZona",
            required: true
        },
        reportes_id: {
            model: "reportes",
            required: true
        },
        empleado_homologador: {
            type: "number",
        }
    },

  customToJSON: function() {
    //Si no se obtiene algun producto asociado, se retorna un objecto
    if(typeof this.productos_zona_id =="number")
      this.productos_zona_id = {
        id: this.productos_zona_id
      };
    if(typeof this.reportes_id =="number")
      this.reportes_id = {
        id: this.reportes_id
      };

    if(this.createdAt){
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if(this.updatedAt){
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  },
  tableName:"reportes_has_productos_zonas",

};
