/**
 Generated by sails-inverse-model
 Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
 */
var moment = require('moment');
module.exports = {
  attributes: {
    name: {type: "string"},
    company: {
      model: "companies",
      required: true,
      columnName: "companias_id",
    },
    //Relaciones
    employee: {
      collection: "employees",
      via: "shop"
    },
    zone: {
      collection: "zones",
      via: "shop"
    }

  },
  customToJSON: function () {
    //Si no se obtiene algun producto asociado, se retorna un objecto
    if (typeof this.company == "number")
      this.company = {
        id: this.company
      };

    if (this.createdAt) {
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if (this.updatedAt) {
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  },
};
