/**
 Generated by sails-inverse-model
 Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
 */
var moment = require('moment');
module.exports = {
  attributes: {
    state: {type: "boolean"},
    manifiesto: {type: "string"},
    message: {type: "string"},
    employee: {
      model: "employees",
      columnName: "employee_id",
      required: true
    },
    shopSource: {
      model: "shops",
      columnName: "shop_source_id",
      required: true
    },
    shopDestination: {
      model: "shops",
      columnName: "shop_destination_id",
      required: true
    },
    //Relaciones muchos a muchos
    products: {
      collection: 'TransfersHasZonesProducts',
      via: 'transfer_id'
    },
    // empleados:{
    //   collection: "empleados",
    //   via: "locales_id"
    // }
  },
  customToJSON: function () {
    //Si no se obtiene algun producto asociado, se retorna un objecto
    if (typeof this.employee == "number")
      this.employee = {
        id: this.employee
      };
    if (typeof this.shopSource == "number")
      this.shopSource = {
        id: this.shopSource
      };
    if (typeof this.shopDestination == "number")
      this.shopDestination = {
        id: this.shopDestination
      };
    if (this.createdAt) {
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if (this.updatedAt) {
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  },
};
