/**
 Generated by sails-inverse-model
 Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
 */
var moment = require('moment');
module.exports = {
  attributes: {
    product: {
      model: "productsHasZones",
      columnName: "products_has_zone_id",
      required: true
    },
    transfer: {
      model: "transfers",
      columnName: "transfer_id",
      required: true
    },
    state: {
      type: "boolean",
    },
  },

  customToJSON: function () {
    //Si no se obtiene algun producto asociado, se retorna un objecto
    if (typeof this.product == "number")
      this.product = {
        id: this.product
      };
    if (typeof this.transfer == "number")
      this.transfer = {
        id: this.transfer
      };

    if (this.createdAt) {
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if (this.updatedAt) {
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  },
  tableName: "transfers_has_zones_products",

  beforeCreate: function (valuesToSet, proceed) {

    ProductosZonaHasTransferencias.findOne({
      productos_zona_id: valuesToSet.productos_zona_id,
      estado: 0
    })
      .then(function (productoZonaHasTransferencia) {
        //No puede existir el mismo producto en transferencia a la vez
        if (productoZonaHasTransferencia)
          return proceed('error_PZHT01');
        else
          return proceed();
      }).catch(function (error) {
      return proceed(error);
    });

  }
};
