/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/

module.exports = {
    attributes: {
        nombre: {
            type: "string",
        },
        epcs_id: {
            model: "epcs",
            required: true
        },
        zonas_id: {
            model: "zonas",
            required: true
        }
    },
  customToJSON: function() {
    //Si no se obtiene algun producto asociado, se retorna un objecto
    if(typeof this.epcs_id =="number")
      this.epcs_id = {
        id: this.epcs_id
      };
    if(typeof this.zonas_id =="number")
      this.zonas_id = {
        id: this.zonas_id
      };

    return this;
  },
};
