/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/

module.exports = {
    attributes: {
        nombre: {
            type: "string",
        },
        epcs_id: {
            model: "epcs",
            required: true
        },
        zonas_id: {
            model: "zonas",
            required: true
        }
    }
};
