/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/
var moment = require('moment');
module.exports = {
    attributes: {
        empleados_id: {
            model: "empleados",
            required: true
        },
        inventarios_id: {
            model: "inventarios",
            required: true
        }
    },
  customToJSON: function() {
    if(typeof this.empleados_id =="number")
      this.empleados_id = {
        id: this.empleados_id
      };
    if(typeof this.inventarios_id =="number")
      this.inventarios_id = {
        id: this.inventarios_id
      };
    if(this.createdAt){
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if(this.updatedAt){
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  },
  tableName:"users_inventarios"
};
