/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/
var moment = require('moment');
module.exports = {
    attributes: {
        users_id: {
            model: "users",
            required: true
        }
    },
  customToJSON: function() {
    if(typeof this.users_id =="number")
      this.users_id = {
        id: this.users_id
      };
    if(this.createdAt){
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if(this.updatedAt){
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }

    return this;
  },
};
