/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/

module.exports = {
    attributes: {
        users_id: {
            model: "users",
            required: true
        }
    },
  customToJSON: function() {
    if(typeof this.users_id =="number")
      this.users_id = {
        id: this.users_id
      };

    return this;
  },
};
