/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/

module.exports = {
    attributes: {
        name: {
            type: "string",
        },
        locales_id: {
            model: "locales",
            required: true
        }

    },
  customToJSON: function() {
    //Si no se obtiene algun producto asociado, se retorna un objecto
    if(typeof this.locales_id =="number")
      this.locales_id = {
        id: this.locales_id
      };
    return this;
  }
};
