#FROM mysql:5.7.19
FROM jamper91/iv_mysql
#ENV MYSQL_DATABASE inventarioReal
#ENV MYSQL_ROOT_PASSWORD gjwQbdRD4ktt
#ENV MYSQL_USER inventarioReal
#ENV MYSQL_PASSWORD gjwQbdRD4ktt
#ADD init.sql /docker-entrypoint-initdb.d/
