/**
 Generated by sails-inverse-model
 Date:Sun Oct 07 2018 11:23:28 GMT+1300 (NZDT)
 */
var moment = require('moment');
module.exports = {
  attributes: {
    name: {
      type: "string",
    },
    user: {
      model: "users",
      columnName: "user_id",
      required: true
    },
    companies: {
      collection: "companies",
      via: "dealer"
    },
  },
  customToJSON: function () {
    if (this.createdAt) {
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if (this.updatedAt) {
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  }
};
