/**
 Generated by sails-inverse-model
 Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
 */
var moment = require('moment');
module.exports = {
  attributes: {
    product: {
      model: "products",
      required: true,
      columnName: "product_id",
    },
    productsHasZone: {
      model: "productsHasZones",
      required: true,
      columnName: "products_has_zone_id",
    },
    user: {
      model: "users",
      required: true,
      columnName: "user_id",
    }

  },
  customToJSON: function () {
    //Si no se obtiene algun producto asociado, se retorna un objecto
    if (typeof this.product == "number"){
      this.product = {
        id: this.product
      };
    }
    if (typeof this.productsHasZones == "number"){
      this.productsHasZones = {
        id: this.productsHasZones
      };
    }
    if (typeof this.user == "number"){
      this.user = {
        id: this.user
      };
    }

    if (this.createdAt) {
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if (this.updatedAt) {
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  },
  tableName: "devolutions_history",
};
