/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/

module.exports = {
    attributes: {
        inventarios_id: {
            type: "number",

            required: true
        },
        productos_id: {
            type: "number",

            required: true
        },
        productos_epcs_id: {
            type: "number",

            required: true
        },
        zonas_id: {
            type: "number",

            required: true
        }
    }
};
