/**
 Generated by sails-inverse-model
 Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
 */
var moment = require('moment');
module.exports = {

  attributes: {
    products: {
      type: 'json'
    },
    shop: {
      model: "Shops",
      required: true,
      columnName: "shop_id"
    }

  },
  customToJSON: function () {
    if (typeof this.shop == "number")
      this.shop = {
        id: this.shop
      };
    if (this.createdAt) {
      this.createdAt = moment(this.createdAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    if (this.updatedAt) {
      this.updatedAt = moment(this.updatedAt).format("YYYY-MM-DDTHH:mm:ss");
    }
    return this;
  },
  tableName: 'inventory_erp'
};
