/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/

module.exports = {
    attributes: {
        fecha: {
            type: "string"
        },
        parcial: {
            type: "number",

        },
        colaborativo: {
            type: "number",

        },
        zonas_id: {
            type: "number",

            required: true
        }
    }
};
