/**
 Generated by sails-inverse-model
 Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
 */
module.exports = {

  attributes: {
    productos_id: {
      type: "number",

      required: true
    },
    zona_id: {
      type: "number",

      required: true
    },
    cantidad: {
      type: "number",

    },
    fecha_ingreso: {
      type: 'ref', columnType: 'datetime', autoCreatedAt: true
    },
    fecha_venta: {
      type: 'ref', columnType: 'datetime',
    },
    fecha_devolucion: {
      type: 'ref', columnType: 'datetime',
    },
    devolucion_observaciones: {
      type: "string"
    },
    devoluciones_id: {
      type: "number",

      required: true
    },
    logs_usuarios: {
      type: "string"
    },
    ventas_id: {
      type: "number",

      required: true
    },
    epcs_id: {
      type: "number",
      required: true
    }

  },
  beforeCreate: function (valuesToSet, proceed) {
    //Valido que el epc sea valido (lo busco por el epc y que el estado sea 0 -sin usar)

    if(Array.isArray(valuesToSet)){
      Epcs.find({
        id: valuesToSet.epcs_id,
        state: 0
      }).then(function (epc) {
        if(epc && epc.length>0){
          epc.state=1;
          epc.save();
          return proceed();
        } else
          return proceed({"error":'Tag no valido bc'});
      }).catch(function (err) {
        return proceed(err)
      });
    }else{
      try{
        Epcs.find({
          id: valuesToSet.epcs_id,
          state: 0
        }).then(function (epc) {
          if(epc && epc.length>0){
            return proceed();
          }else
            return proceed({"error":'Tag no valido bc'});
        }).catch(function (err) {
          return proceed(err)
        });
      }catch(err){
        console.error(err);
      }

    }

  },
  tableName: 'productos_zona'
};
