/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/

module.exports = {
    attributes: {
        productos_id: {
            type: "number",

            required: true
        },
        zona_id: {
            type: "number",

            required: true
        },
        cantidad: {
            type: "number",

        },
        precio_costo: {
          type: "number"
        },
        precio_venta: {
          type: "number"
        },
        fecha_ingreso: {
            type: "string"
        },
        fecha_venta: {
            type: "string"
        },
        fecha_devolucion: {
            type: "string"
        },
        devolucion_observaciones: {
            type: "string"
        },
        devoluciones_id: {
            type: "number",

            required: true
        },
        logs_usuarios: {
            type: "string"
        },
        ventas_id: {
            type: "number",

            required: true
        }
    }
};
