/**
	Generated by sails-inverse-model
	Date:Sun Oct 07 2018 11:23:29 GMT+1300 (NZDT)
*/

module.exports = {
    attributes: {
        productos_zona_id: {
            model: "productosZona",
            required: true
        },
        transferencias_id: {
            model: "transferencias",
            required: true
        },
        estado: {
            type: "number",
        },
    }
};
